spring:
  redis:
    database: 0
    host: 192.168.1.156
    port: 6379
    password: pamirs@2020
    lettuce:
      pool:
        # ????1
        min-idle: 1
        # ????8
        max-idle: 8
        # ?????8
        max-active: 8
        # ??????3000??
        max-wait: 3000
      shutdown-timeout: 1000
    connect-timeout: 2000
    timeout: 2000

rocketmq:
  producer:
    group: sanyouProducer
  name-server: 192.168.1.151:9876

